title: ZDDHUB
slogan: Just for fun
author: zddhub
email: zddhub@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

url: https://zddhub.github.io
baseurl: ""

twitter_username: zddhub
github_username:  zddhub

gravid:
  date_format: "%m/%d/%Y"

language: en
enable_reward: false

# Build settings
markdown: kramdown
theme: gravid
exclude:
  - Gemfile
  - Gemfile.lock
